### ISSUE TITLE
Could not find the following Boost libraries: boost_signals

### ISSUE THREAD

**Issue by fiedl** [fiedl/hole-ice-install#3]
Running `cmake` results in an error, because a boost library is missing.

```
# cmake

    default: -- Boost
    default: -- Boost version: 1.69.0
    default: -- Looking for pthread.h
    default: -- Looking for pthread.h - found
    default: -- Looking for pthread_create
    default: -- Looking for pthread_create - found
    default: -- Found Threads: TRUE
    default: -- Could NOT find Boost
    default: -- Boost version: 1.69.0
    default: Boost include path: /usr/local/include
    default: Could not find the following Boost libraries:
    default:         boost_signals
    default: Some (but not all) of the required Boost libraries were found. You may need to install these additional Boost libraries. Alternatively, set BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT to the location of Boost.
    default: CMake Error at /usr/local/Cellar/cmake/3.14.1/share/cmake/Modules/FindBoost.cmake:2132 (message):
    default:   Unable to find the requested Boost libraries.
    default:
    default:   Unable to find the Boost header files.  Please set BOOST_ROOT to the root
    default:   directory containing Boost or BOOST_INCLUDEDIR to the directory containing
    default:   Boost's headers.
    default: Call Stack (most recent call first):
    default:   cmake/tools/boost.cmake:66 (find_package)
    default:   cmake/tools.cmake:60 (include)
    default:   cmake/toplevel.cmake:95 (include)
    default:   CMakeLists.txt:22 (include)

    default: -- Configuring projects:
    default: --
    default: -- + DOMLauncher
    default: -- +-- python [symlinks]
    default: CMake Error at cmake/tools.cmake:71 (message):
    default:   Attempt to use tool 'boost' which wasn't found
    default: Call Stack (most recent call first):
    default:   cmake/tools.cmake:112 (use_tool)
    default:   cmake/project.cmake:254 (use_tools)
    default:   DOMLauncher/CMakeLists.txt:25 (i3_add_library)
    default: -- Configuring incomplete, errors occurred!
    default: See also "/Users/vagrant/icecube/software/icecube-simulation-V06-01-01/debug_build/CMakeFiles/CMakeOutput.log".
    default: See also "/Users/vagrant/icecube/software/icecube-simulation-V06-01-01/debug_build/CMakeFiles/CMakeError.log".
```

**How to reproduce**: Clone this repository and provide svn credentials as shown in https://github.com/fiedl/hole-ice-install#automated-build-using-vagrant. Then run `vagrant up`. The console output will show the above error.

Also seen on travis: https://travis-ci.org/fiedl/hole-ice-install/builds/517758863
